apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
spec:
  selector:
    matchLabels:
      app: management
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: management
        tier: frontend
        track: stable
    spec:
      containers:
        - name: management
          image: sonicblue/iot-management
          env:
            - name: DRIVER
              value: "postgres"
            - name: DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-man
                  key: DATASOURCE
            - name: HOST
              value: "management:8010"
            - name: SCHEME
              value: "http"
            - name: IDENTITYAPI
              value: "http://identity:8030/v1/"
            - name: DEVICETWINAPI
              value: "http://devicetwin:8040/v1/"
            - name: STOREURL
              value: "https://api.snapcraft.io/api/v1/"
          ports:
            - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: management
spec:
  selector:
    app: management
    tier: frontend
  ports:
    - port: 8010
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: management-port
spec:
  selector:
    app: management
  type: NodePort
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      nodePort: 30100
      protocol: TCP